Add files via upload

diff --git a/.github/workflows/高通410 immortalwrt.yml b/.github/workflows/高通410 immortalwrt.yml
--- a/.github/workflows/高通410 immortalwrt.yml
+++ b/.github/workflows/高通410 immortalwrt.yml
@@ -1,15 +1,3 @@
-#
-# https://github.com/P3TERX/Actions-OpenWrt
-#
-# File: .github/workflows/openwrt-bulder.yml
-# Description: Build OpenWrt using GitHub Actions
-#
-# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
-#
-# This is free software, licensed under the MIT License.
-# See /LICENSE for more information.
-#
-
 name: immortalwrt_高通410系列
 
 on:
@@ -19,48 +7,52 @@ on:
       ssh:
         description: 'SSH connection to Actions'
         required: false
-        default: 'false'
+        default: false
+        type: boolean
+      log_switch:
+        description: "编译日志开关"
+        required: false
+        default: false
+        type: boolean
+
+
 
 env:
+  CONFIG_FILE: 'config/config_small'
   REPO_URL: https://github.com/xuxin1955/immortalwrt
   REPO_BRANCH: master
   FEEDS_CONF: feeds.conf.default
-  CONFIG_FILE: config_small
   DIY_P1_SH: diy-part1.sh
-  DIY_P2_SH: diy-part2.sh
-  UPLOAD_BIN_DIR: false
   UPLOAD_FIRMWARE: true
   UPLOAD_RELEASE: true
   TZ: Asia/Shanghai
-
+  
 jobs:
   build:
-    runs-on: ubuntu-latest  
+    runs-on: ubuntu-latest
+
     steps:
     - name: Checkout
-      uses: actions/checkout@main
+      uses: actions/checkout@master
 
     - name: Show hardware info
       run: |
         chmod 755 ./scripts/show_hardware_info.sh
         ./scripts/show_hardware_info.sh
-  
-    - name: Free Disk Space (Ubuntu)
+
+    - name: Free disk space
       uses: jlumbroso/free-disk-space@main
       with:
-        # this might remove tools that are actually needed,
-        # if set to "true" but frees about 6 GB
-        tool-cache: false
-
-        # all of these default to true, but feel free to set to
-        # "false" if necessary for your workflow
+        tool-cache: true
         android: true
         dotnet: true
-        haskell: true
-        large-packages: true
-        docker-images: true
-        swap-storage: true
+
+    - name: space usage check  
+      run: |
+        df -H
+
     - name: Initialization environment
+      id: init
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
@@ -78,10 +70,9 @@ jobs:
         else
         echo "❌ mkbootimg not found in PATH!"
         fi
-
-        sudo timedatectl set-timezone "$TZ"
-        sudo chmod 777 /mnt
-        df -hT
+        
+        sudo timedatectl set-timezone "${TZ}"
+        echo "status=success" >> ${GITHUB_OUTPUT}
         
     - name: Ensure Python build tools
       run: |
@@ -89,17 +80,31 @@ jobs:
         python3 -m pip --version
         python3 -c "import setuptools.build_meta; print('setuptools.build_meta OK')"
         python3 -m pip install Unidecode
-
+        
+        
     - name: Clone source code
-      working-directory: /mnt
+      id: codes
+      if: steps.init.outputs.status == 'success' && success()
       run: |
-        df -hT $PWD
-        git clone $REPO_URL -b $REPO_BRANCH openwrt
-        ln -sf /mnt/openwrt $GITHUB_WORKSPACE/openwrt
-
+        git clone --depth 1 "$REPO_URL" -b "$REPO_BRANCH" openwrt
+        if [ -n "$GITHUB_OUTPUT" ]; then
+        echo "status=success" >> "$GITHUB_OUTPUT"
+        else
+        echo "::set-output name=status::success"
+        fi
+       
     - name:  files 克隆大法
       run: cp -r files openwrt/files
-
+       
+    - name: Free up disk space
+      run: |
+        sudo mkdir -p /mnt/openwrt/{dl,staging_dir,build_dir}
+        sudo chown -R $USER:$GROUPS /mnt/openwrt
+        ln -sfn /mnt/openwrt/dl openwrt/dl
+        ln -sfn /mnt/openwrt/staging_dir openwrt/staging_dir
+        ln -sfn /mnt/openwrt/build_dir openwrt/build_dir
+        df -H
+        
     - name: Load custom feeds
       run: |
         [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
@@ -115,78 +120,59 @@ jobs:
        ./scripts/feeds install -d y -p istore luci-app-store
 
 
-    - name: Update feeds
-      run: cd openwrt && ./scripts/feeds update -a
-
-    - name: Install feeds
-      run: cd openwrt && ./scripts/feeds install -a -f
-
-    - name: Load custom configuration
+    - name: Update & Install feeds
+      working-directory: ./openwrt
       run: |
-        [ -e files ] && mv files openwrt/files
-        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
-        chmod +x $DIY_P2_SH
-        cd openwrt
-        $GITHUB_WORKSPACE/$DIY_P2_SH
+        ./scripts/feeds update -a
+        
+        ./scripts/feeds install -a -f
+        
+
+    - name: Configuration Customization
+      run: |
+        cp -fv "${CONFIG_FILE}" openwrt/.config
+        cd openwrt && make defconfig
         
     - name: SSH connection to Actions
-      uses: csexton/debugger-action@master
-      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
+        uses: csexton/debugger-action@master
+        if: ${{ inputs.ssh || contains(github.event.action, 'ssh') }}
       
-    - name: Config defconfig
-      id: config
-      run: |
-       cd openwrt
-       make defconfig
-       
+        
     - name: Download package
-      id: package
+      working-directory: ./openwrt
       run: |
-        cd openwrt
-        make download -j4 V=s
-        find dl -size -1024c -exec ls -l {} \;
-        find dl -size -1024c -exec rm -f {} \;
-
-    - name: 查看 openwrt 目录中的文件
+        make download -j$(nproc) || { echo "Download failed"; exit 1; }
+        find dl -size -1024c -delete
+        
+    - name: 查看 openwrt 根目录
       run: ls -la openwrt/
       
     - name: 自动上传编译配置
       uses: actions/upload-artifact@v4
       with:
-       name: pre-build-config
+       name: build-config
        path: |
         openwrt/.config
         openwrt/feeds.conf.default
 
-
-    - name: Compile the firmware
+    - name: Compile the OpenWrt
       id: compile
       run: |
-        cd openwrt
-        echo -e "$(nproc) thread compile"
-        make -j$(nproc) || make -j1 || make -j1 V=s
-        echo "status=success" >> $GITHUB_OUTPUT
+        cd openwrt/
+        make defconfig
+        if [[ "${{ inputs.log_switch }}" == "true" ]]; then
+            make -j1 V=s
+        else
+            make -j$(nproc)
+        fi
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-
-    - name: Check space usage
-      if: (!cancelled())
-      run: df -hT
-
-    - name: Fix Git buffer
-      run: git config --global http.postBuffer 524288000
-
-    - name: Upload bin directory
-      uses: actions/upload-artifact@main
-      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
-      with:
-        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: openwrt/bin
-
+        echo "status=success" >> $GITHUB_OUTPUT
+        
     - name: Organize files
       id: organize
-      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+      if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success'
       run: |
         cd openwrt/bin/targets/*/*
         rm -rf packages
@@ -198,23 +184,26 @@ jobs:
       if: steps.organize.outputs.status == 'success' && !cancelled()
       with:
         name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: ${{ env.FIRMWARE }}
+        path: ${{ env.FIRMWARE }}/*
 
     - name: Generate release tag
       id: tag
-      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success'
       run: |
         echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
-        touch release.txt
-        [ ${UPLOAD_GOFILE} = true && ${{ steps.gofile.outputs.url }} ] && echo "🔗 [GoFile](${{ steps.gofile.outputs.url }})" >> release.txt
-        echo "## Immortalwrt24.10 高通410系列" >> release.txt
-        echo "- 管理地址:192.168.1.1" >> release.txt
-        echo "  默认用户:root" >> release.txt
-        echo "  默认密码:空" >> release.txt
+        cat <<EOF > release.txt
+        🚀 OpenWrt firmware for XG_040G_MD
+        ----------------------
+        设备: 高通410随身WIFI
+        时间: $(date +"%Y-%m-%d %H:%M")
+        内核版本: 6.12.X
+        源码仓库: $REPO_URL
+        分支: $REPO_BRANCH
+        EOF
         echo "status=success" >> $GITHUB_OUTPUT
 
     - name: Upload firmware to release
-      uses: softprops/action-gh-release@master
+      uses: softprops/action-gh-release@v1
       if: steps.tag.outputs.status == 'success' && !cancelled()
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -224,15 +213,8 @@ jobs:
         files: ${{ env.FIRMWARE }}/*
 
     - name: Delete workflow runs
-      uses: Mattraks/delete-workflow-runs@main
+      uses: LeeHe-gif/delete-workflow-runs@main
       with:
-        retain_days: 0
-        keep_minimum_runs: 7
-    - name: Remove old Releases
-      uses: dev-drprasad/delete-older-releases@master
-      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
-      with:
-        keep_latest: 7
-        delete_tags: true
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        retain_days: 7
+        keep_minimum_runs: 5
+        token: ${{ secrets.GITHUB_TOKEN }}
